### ISSUE TITLE
Put this plugin on Bower

### ISSUE THREAD

**Issue by bryanbraun** [handsontable/handsontable-ruleJS#12]
The other handsontable libraries (handsontable, ruleJS, etc.) are available for download via bower. It would be nice for this plugin to be available via bower as well, to make it easy to manage all of them in the same way.

**Comment by motin** [comment]
In the meanwhile: 

    bower install https://github.com/handsontable/handsontable-ruleJS.git --save

**Comment by bryanbraun** [comment]
Nice! I wasn't aware that was possible. Thanks. :smile:
