### ISSUE TITLE
Missing afterRemoveRow() and afterRemoveCol() in handsontable.formula.js

### ISSUE THREAD

**Issue by Atulchirame** [handsontable/handsontable-ruleJS#16]
On removing row and colomn, handsontable is running hooks "afterRemoveRow" and "afterRemoveCol" but same hooks are not handled in handsontable.formula.js Hence no formula adjustment on remove row and column.

( Note :- There should be hooks entry for above twos like we have for afterCreateRow(), afterCreateCol() etc. you can see formula adjustment on create row and column)

Please suggest how to do this ? ( urgently looking for solution :( )

Thanks,
Atul

**Comment by Atulchirame** [comment]
Anyone ?

**Comment by cyygit** [comment]
To solve this, I changed files handsontable.formula.js and ruleJS.all.full.js, and modified a lot of code.

**Comment by Atulchirame** [comment]
I am also modifying existing code. I am on very tight deadline.
It will be very grateful & helpful if you could share your code (these two modified files ).
EmailId : atulchirame@gmail.com

Thanks,
Atul

**Comment by ankitddit** [comment]
Hi guys, i have a problem  with this formula rendere. I am using a container with fix width and height. My formula does not apply to all rows.

**Comment by shadeeka** [comment]
hi, I am having the same issue, can anybody help me please @cyygit , i have changes handsontable.formula.js but could not figure out a way to fix the problem
any help would be appreciate, thanks

**Comment by cyygit** [comment]
I changed files handsontable.formula.js and ruleJS.all.full.js, you can download them from https://github.com/cyygit/handsontable-ruleJS .  @shadeeka

**Comment by shadeeka** [comment]
@cyygit 
thank you very much
