### ISSUE TITLE
Formula SUMIFS doesn't work correctly

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable-ruleJS#21]
According to https://github.com/handsontable/handsontable/issues/2904 SUMIFS formula does not provide desired results.

Demo : http://handsontable.github.io/ruleJS/ parser
for formula `SUMIFS(A1:B1, C1:C5, '>99')` result should be `3` not `0`

**Comment by Vertek** [comment]
can i ask when this bug will be fix?

**Comment by AMBudnik** [comment]
I would really want to give you an approximate date but currently all our programmers are developing final touches for Handsontable PRO.

**Comment by Vertek** [comment]
Is there anything known about this bug? For sprint time is ending and i must use this formule in my code before the sprint is end. Maybe some alternative that i can use instead of this formule?
