### ISSUE TITLE
Remove/Insert row data complications.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable-ruleJS#27]
go to: http://handsontable.github.io/handsontable-ruleJS/
1. Delete row no 5
2. Open contextMenu at 5 row and choose 'insert row above'

result: 2 rows added:
- one empty
- one with formulas in B6 and C6 copied from line 5 before removing it and changed for bigger range of cells.

**Comment by billcollis** [comment]
this is caused by the issue I raised in #26, but no response yet to that
