### ISSUE TITLE
Missing recursive resolution

### ISSUE THREAD

**Issue by Stnaire** [handsontable/handsontable-ruleJS#28]
The plugin doesn't work for more than 1 recursive resolution as demonstrated in the following JSFiddle: 

http://jsfiddle.net/71o23gp0/3/

I'm looking for a way to patch it.

Regards.

**Comment by Stnaire** [comment]
I think I've patched it, I'm sure there is a better way to do it but at least it seems to work now.
You can find the result here : 

http://jsfiddle.net/71o23gp0/6/

Cheers.

**Comment by gm3h** [comment]
Thanks @Stnaire, you really save my life...
