### ISSUE TITLE
How to create new formulas?

### ISSUE THREAD

**Issue by JerryYangJin** [handsontable/handsontable-ruleJS#34]
Hello

I'm planning to use `handsontable` for my project, I need to create new formulas that's not in [existing supported forumlas](http://handsontable.github.io/ruleJS/), is there any document, sample or process that I can follow to do this?

Thanks!

**Comment by axl163** [comment]
Have you found a solution to creating new formulas? An ugly way that worked for me was to add the formulas directly in the handsontable.full.js file and add the formula name to the SUPPORTED_FORMULAS variable. Of course, doing this will break any future updates of the library file. I was hoping for something cleaner that will allow us to extend the functionality.

**Comment by JerryYangJin** [comment]
@axl163 thanks for the update!
I added a few finance formulas, like `NPV`, `PMT` etc, to `SUPPORTED_FOULAS`, but it doesn't work, formula returns `NaN`
do you by any chance have a solution for that? thanks!

**Comment by JerryYangJin** [comment]
`formular-parser` has finance formulas
