### ISSUE TITLE
some formulas having reference chain to other cells are not getting evaluated although are working

### ISSUE THREAD

**Issue by shaludhaka** [handsontable/handsontable-ruleJS#36]
| A | B | C | D | E | F | G | H | I | J | K | L | M
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |   |   |   |   | If latest year is provisional
  | Note: | Cells marked in blue are editable |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | Particulars | As per audited financial (A) | As per stock statement (B) | Excess of stock statement over financial statement |   |   |   |   |   |   |   | Particulars
  |   |   |   | % Variance = [(B-A)/A] % |   |   |   |  
  | Inventory | =ROUND(0+0+0+0+0+0,2) | 0 | 66600.00% |   |   |   |   |   |   |   | Inventory
  | Debtors below 180 days | 0 | 0 | 77700.00% |   |   |   |   |   |   |   | Debtors below 180 days
  | Debtors above 180 days | 0 |   | 0.00% |   |   |   |   |   |   |   | Debtors above 180 days
  | Total debtors | =Y7+Y8 | 0 | 0.00% |   |   |   |   |   |   |   | Total debtors
  | Is stock statement available? | Y |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | Particulars | Amount |   | As % of TOI |   |   | Holding period |   |   |   |   | Particulars
  |   | -1 | 0 | =Y13 | =Z13 | Change | =Y13 | =Z13 | Change in days |   |   |  
  |   |   |   |   |   | (B-A) % |   |   |   |   |   |  
  |   |   |   |   |   | A |   |   |   |   |   |  
  | TOI | =ROUND(ROUND(SUM(0,0),2)-0,2)+0 | =ROUND(ROUND(SUM(0,0),2)-0,2)+0 |   |   |   |   |   |   |   |   | TOI
  | Inventory | =ROUND(0+0+0+0+0+0,2) | =ROUND(0+0+0+0+0+0,2) | 171600.00% | 171600.00% | **=(AB17-AA17)/AA17 | =(AA17*365*12/12) | =(AB17*365*12/12) | =AE17-AD17 |   |   | Inventory**
  | Unbilled revenue | 0 | 0 | 181600.00% | 181600.00% | =(AB18-AA18)/AA18 | =(AA18*365*12/12) | =(AB18*365*12/12) | =AE18-AD18 |   |   | Unbilled revenue
  | Total receivables | 0 | 0 | 191600.00% | 191600.00% | =(AB19-AA19)/AA19 | =(AA19*365*12/12) | =(AB19*365*12/12) | =AE19-AD19 |   |   | Total receivables
  | Receivables > 6 months | 0 | 0 | 201600.00% | 201600.00% | =(AB20-AA20)/AA20 | =(AA20*365*12/12) | =(AB20*365*12/12) | =AE20-AD20 |   |   | Receivables > 6 months
  | Other current assets | =ROUND(0+0+0+0+0+0+0+ROUND(0+0+0+0+0+0,2)+0+0+ROUND(SUM(0,0,0,0+0+0+0+0+0+0+0+0,0),2),2)-(Y17+Y18+Y19-Y20+0+0+0+0) | =ROUND(0+0+0+0+0+0+0+ROUND(0+0+0+0+0+0,2)+0+0+ROUND(SUM(0,0,0,0+0+0+0+0+0+0+0+0,0),2),2)-(Z17+Z18+Z19-Z20+0+0+0+0) | 211600.00% | 211600.00% | =(AB21-AA21)/AA21 | =(AA21*365*12/12) | =(AB21*365*12/12) | =AE21-AD21 |   |   | Other current assets
  | WCBF | =ROUND(0+0+0,2) | =ROUND(0+0+0,2) | 221600.00% | 221600.00% | =(AB22-AA22)/AA22 | =(AA22*365*12/12) | =(AB22*365*12/12) | =AE22-AD22 |   |   | WCBF
  |   |   |   |   |   |

**Comment by AMBudnik** [comment]
Thank you very much for sharing an issue @shaludhaka 
However, we do not maintain the project.
