### ISSUE TITLE
i am trying to store the cellvalue into database 

### ISSUE THREAD

**Issue by vinothmathew0** [handsontable/handsontable-ruleJS#37]
I am using handsontable for a month. if i am trying to save the values in to database it is store the formulas, not the cellvalue. i want to save the cellValue instead of formula handsonetable. i am having 198 rows in the sheet, i cant use, 
hot.plugin.helper.cellValue('C51');
to all the cells  so please help me to do with in hot.getData();

**Comment by AMBudnik** [comment]
Hi @vinothmathew0 
We do not update the library anymore. However, you should be able to get the formula by using the `instance.getSourceDataAtCell(row, col)` method.
