### ISSUE TITLE
error can't be automatically refreshed

### ISSUE THREAD

**Issue by cyygit** [handsontable/handsontable-ruleJS#8]
When i use JSON data for handsontable, I have a formula ‘=A1/A2’,and The 0 is the value of A2, then the #VALUE! error occurred, then i change value of A2 to 1 or other not 0 value, my formula has correct，but the #VALUE! error still exists, the error is not be automatically refresh.
But when i use array data for handsontalbe, above issue does not exist, error can be refreshed.
sorry for my poor english, Anyone has a solution？

**Comment by cyygit** [comment]
I have to change the source code  to solve this problem.
handsontable.formula.js
line 129 added:
		  var columns = instance.getSettings().columns;
		  if (columns != null && columns.length > 0 && columns[0].data != null) {
			 for (var i=0;i<columns.length;i++) {
				if (col == columns[i].data) {
					col = i;
					break;
				}
			 }
		  }

then the issue does not exist.

**Comment by nyon** [comment]
I have the same error with "#REF!" cell errors. I fixed it with the following code:

    var cellId = instance.plugin.utils.translateCellCoords({row: row, col: col-1});

instead of 

    var cellId = instance.plugin.utils.translateCellCoords({row: row, col: col  });

in line 113 (handsontable.formula.js)

**Comment by cyygit** [comment]
Maybe our problem are not same, because your changes can not fix my problem.
when i has this problem, the col value is string like ‘age’, not a number.

**Comment by awsp** [comment]
+1
Got the same problem. 

My case is when using autofill with formulas, when one of the cells required in the formulas is empty and does not re-apply to the formula I have.
